version: "3.8"

services:
  traefik:
    image: traefik:latest
    container_name: infra_traefik
    env_file:
      - .env
    command:
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesResolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesResolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.le.acme.tlsChallenge=true
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: infra_grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${PROJECT_HOST}`) && PathPrefix(`/grafana`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls.certresolver=le"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${METRICS_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${METRICS_PASSWORD}
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./conf/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    networks:
      - monitor

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: infra_prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./metrics_pwd:/etc/prometheus/metrics_pwd:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitor

  loki:
    image: grafana/loki:latest
    container_name: infra_loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`${PROJECT_HOST}`) && PathPrefix(`/loki`)"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    volumes:
      - ./conf/loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      - monitor

volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  monitor:
    driver: bridge
