apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram_receiver
        type: telegram
        settings:
          chatid: ${TELEGRAM_CHAT_ID_STR}
          message: |
            🔴 *Сервис недоступен*
            Сервис: {{ index .Labels "instance" }}
            Статус: {{ .Status }}
            {{ if .EndsAt }}Восстановлен: {{ .EndsAt }}{{ end }}
        secureSettings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
        disableResolveMessage: false
